return {
  -- {
  --   "hrsh7th/cmp-nvim-lsp",
  -- },
  -- {
  --   "L3MON4D3/LuaSnip",
  --   dependencies = {
  --     "saadparwaiz1/cmp_luasnip",
  --     "rafamadriz/friendly-snippets",
  --   },
  -- },
  -- {
  --   "ray-x/lsp_signature.nvim",
  --   event = "InsertEnter",
  --   opts = {
  --     hint_enable = false,
  --     close_timeout = 100,
  --   },
  -- },
  -- {
  --   "windwp/nvim-autopairs",
  --   event = "InsertEnter",
  --   config = true,
  -- },
  -- {
  --   "hrsh7th/nvim-cmp",
  --   config = function()
  --     local cmp = require("cmp")
  --     local cmp_autopairs = require("nvim-autopairs.completion.cmp")
  --     local luasnip = require("luasnip")
  --     require("luasnip.loaders.from_vscode").lazy_load()
  --
  --     cmp.setup({
  --       snippet = {
  --         expand = function(args)
  --           require("luasnip").lsp_expand(args.body)
  --         end,
  --       },
  --       completion = {},
  --       window = {
  --         completion = cmp.config.window.bordered(),
  --         documentation = cmp.config.window.bordered(),
  --       },
  --       mapping = cmp.mapping.preset.insert({
  --         ["<C-b>"] = cmp.mapping.scroll_docs(-4),
  --         ["<C-f>"] = cmp.mapping.scroll_docs(4),
  --         ["<C-Space>"] = cmp.mapping.complete(),
  --         ["<C-e>"] = cmp.mapping.abort(),
  --         ['<Tab>'] = cmp.mapping(function(fallback)
  --           if cmp.visible() then
  --             if luasnip.expandable() then
  --               luasnip.expand()
  --             else
  --               cmp.confirm({
  --                 select = true,
  --               })
  --             end
  --           else
  --             fallback()
  --           end
  --         end),
  --       }),
  --       sources = cmp.config.sources({
  --         { name = "nvim_lsp" },
  --         { name = "luasnip" }, -- For luasnip users.
  --       }, {
  --           { name = "buffer" },
  --         })
  --     })
  --
  --     cmp.event:on(
  --       "confirm_done",
  --       cmp_autopairs.on_confirm_done()
  --     )
  --   end,
  -- },
}
