return {
  -- "mfussenegger/nvim-dap",
  -- dependencies = {
  --   "rcarriga/nvim-dap-ui",
  --   "nvim-neotest/nvim-nio",
  --   "mfussenegger/nvim-dap-python",
  -- },
  -- config = function()
  --   local dap = require("dap")
  --   local dapui = require("dapui")
  --
  --   require("dapui").setup()
  --
  --   -- language setups
  --   -- c stuff
  --   dap.adapters.codelldb = {
  --     type = "executable",
  --     command = "codelldb",
  --   }
  --
  --   dap.configurations.c = {
  --     name = "Launch file",
  --     type = "codelldb",
  --     request = "launch",
  --     program = function()
  --       return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
  --     end,
  --     cwd = '${workspaceFolder}',
  --     stopOnEntry = false,
  --   }
  --
  --   -- python stuff
  --   require("dap-python").setup("python3")
  --
  --   -- godot stuff
  --   dap.adapters.godot = {
  --     type = "server",
  --     host = "127.0.0.1",
  --     port = 6006,
  --   }
  --
  --   dap.configurations.gdscript = {
  --     {
  --       type = "godot",
  --       request = "launch",
  --       name = "Launch scene",
  --       project = "${workspaceFolder}",
  --       launch_scene = true,
  --     }
  --   }
  --
  --   -- other settings and keybindings
  --   dap.listeners.before.attach.dapui_config = function()
  --     dapui.open()
  --   end
  --
  --   dap.listeners.before.launch.dapui_config = function()
  --     dapui.open()
  --   end
  --
  --   dap.listeners.before.event_terminated.dapui_config = function()
  --     dapui.close()
  --   end
  --
  --   dap.listeners.before.event_exited.dapui_config = function()
  --     dapui.close()
  --   end
  --
  --   vim.keymap.set("n", "<leader>b", dap.toggle_breakpoint, {})
  --   vim.keymap.set("n", "<leader>dc", dap.continue, {})
  -- end,
}
